---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dbs2go-global-r-filebeat-config
  namespace: dbs
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /data/srv/logs/dbs/*${MY_POD_NAME}*
      ignore_older: 1h
      scan_frequency: 10s
      backoff: 5s
      max_backoff: 10s
    output.console:
      codec.format:
        string: '%{[message]} - Podname=${MY_POD_NAME}'
        pretty: false
    queue.mem:
      events: 65536
    logging.metrics.enabled: false
---
kind: Service
apiVersion: v1
metadata:
  name: dbs2go-global-r
  namespace: dbs
spec:
  selector:
    app: dbs2go-global-r
  ports:
    - port: 9252
      targetPort: 9252
      name: dbs
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: dbs2go-global-r
  name: dbs2go-global-r
  namespace: dbs
spec:
  selector:
    matchLabels:
      app: dbs2go-global-r
  replicas: 1 #PROD# 5
  template:
    metadata:
      labels:
        app: dbs2go-global-r
        env: k8s #k8s#
        job: dbs2go-global-r
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: "/dbs/prod/global/DBSReader/metrics"
        prometheus.io/port: "9252"
    spec:
#PROD#      initContainers:
#PROD#      - command:
#PROD#        - sh
#PROD#        - -c
#PROD#        - |
#PROD#          apt-get update && apt-get install -y sudo && apt-get clean && \
#PROD#          chmod 0777 /data/srv/logs/dbs && chown 1000:1000 /data/srv/logs/dbs
        image: ubuntu
        imagePullPolicy: Always
        name: init-install-sudo
        resources: {}
        securityContext:
          runAsGroup: 0
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/srv/logs/dbs
          name: logs
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 2000
      containers:
      - image: registry.cern.ch/cmsweb/dbs2go #imagetag
        name: dbs2go-global-r
        imagePullPolicy: Always
        env:
        - name: X509_USER_PROXY
          value: /etc/proxy/proxy
        - name: TNS_ADMIN
          value: /etc/tnsnames.ora          
        command:
        - /data/run.sh
        resources:
          requests:
            memory: "100Mi"
            cpu: "200m"
          limits:
            memory: "500Mi"
            cpu: "4000m"
        livenessProbe:
          httpGet:
            path: /dbs/prod/global/DBSReader/healthz
            port: 9252
            httpHeaders:
            - name: Accept
              value: application/json
          initialDelaySeconds: 120
          periodSeconds: 10
        ports:
        - containerPort: 9252
          protocol: TCP
          name: dbs
        command:
        - /data/run.sh
        volumeMounts:
        - name: proxy-secrets
          mountPath: /etc/proxy
          readOnly: true
        - name: secrets
          mountPath: /etc/secrets
          readOnly: true
        - name: robot-secrets
          mountPath: /etc/robots
          readOnly: true
        - name: hmac-secrets
          mountPath: /etc/hmac
          readOnly: true
        - name: token-secrets
          mountPath: /etc/token
          readOnly: true
        - name: tnsnames
          mountPath: /etc/tnsnames.ora
          subPath: tnsnames.ora          
#PROD#  - name: logs
#PROD#    mountPath: /data/srv/logs/dbs
        securityContext:
          allowPrivilegeEscalation: false
#PROD#- name: dbs2go-global-r-filebeat
#PROD#  image: docker.elastic.co/beats/filebeat:7.12.0
#PROD#  args: [
#PROD#    "-c", "/etc/filebeat.yml",
#PROD#    "-e",
#PROD#  ]
#PROD#  env:
#PROD#  - name: MY_POD_NAME
#PROD#    valueFrom:
#PROD#      fieldRef:
#PROD#        apiVersion: v1
#PROD#        fieldPath: metadata.name
#PROD#  resources:
#PROD#    requests:
#PROD#      memory: "50Mi"
#PROD#      cpu: "50m"
#PROD#  volumeMounts:
#PROD#  - name: logs
#PROD#    mountPath: /data/srv/logs/dbs
#PROD#  - name: config
#PROD#    mountPath: /etc/filebeat.yml
#PROD#    readOnly: true
#PROD#    subPath: filebeat.yml
#PROD#  - name: data
#PROD#    mountPath: /usr/share/filebeat/data
#PROD#  - name: varlog
#PROD#    mountPath: /var/log
#PROD#  - name: varlibdockercontainers
#PROD#    mountPath: /var/lib/docker/containers
#PROD#    readOnly: true
#PROD#  securityContext:
#PROD#    allowPrivilegeEscalation: false
      volumes:
      - name: proxy-secrets
        secret:
          secretName: proxy-secrets
      - name: robot-secrets
        secret:
          secretName: robot-secrets
      - name: hmac-secrets
        secret:
          secretName: hmac-secrets
      - name: secrets
        secret:
          secretName: dbs2go-global-r-secrets
      - name: tnsnames
        configMap:
          name: tnsnames-config
      - name: token-secrets
        secret:
          secretName: token-secrets          
#PROD#- name: logs
#PROD#  persistentVolumeClaim:
#PROD#      claimName: logs-cephfs-claim-dbs
#PROD#- name: varlog
#PROD#  hostPath:
#PROD#    path: /var/log
#PROD#- name: varlibdockercontainers
#PROD#  hostPath:
#PROD#    path: /var/lib/docker/containers
#PROD#- name: config
#PROD#  configMap:
#PROD#    defaultMode: 0640
#PROD#    name: dbs2go-global-r-filebeat-config
#PROD#- name: data
#PROD#  emptyDir: {}
